CREATE USER IF NOT EXISTS 'marchena'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON blog_db.* TO 'marchena'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    imgSrc VARCHAR(255) NULL,
    pelicula VARCHAR(255) NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
